export const COUNTRIES = ["India"] as const;

export const INDIA_STATES_CITIES: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chilakaluripet",
    "Chittoor",
    "Eluru",
    "Guntur",
    "Kadapa",
    "Kakinada",
    "Kurnool",
    "Machilipatnam",
    "Nandyal",
    "Nellore",
    "Ongole",
    "Proddatur",
    "Rajahmundry",
    "Srikakulam",
    "Tenali",
    "Tirupati",
    "Vijayawada",
    "Visakhapatnam",
    "Vizianagaram",
  ],
  "Arunachal Pradesh": [
    "Along",
    "Bomdila",
    "Changlang",
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Roing",
    "Tawang",
    "Tezu",
    "Ziro",
  ],
  Assam: [
    "Barpeta",
    "Bongaigaon",
    "Dhubri",
    "Dibrugarh",
    "Diphu",
    "Goalpara",
    "Guwahati",
    "Jorhat",
    "Karimganj",
    "Nagaon",
    "North Lakhimpur",
    "Silchar",
    "Sivasagar",
    "Tezpur",
    "Tinsukia",
  ],
  Bihar: [
    "Arrah",
    "Begusarai",
    "Bettiah",
    "Bhagalpur",
    "Bihar Sharif",
    "Buxar",
    "Chapra",
    "Darbhanga",
    "Gaya",
    "Gopalganj",
    "Hajipur",
    "Katihar",
    "Motihari",
    "Munger",
    "Muzaffarpur",
    "Patna",
    "Purnia",
    "Samastipur",
    "Sasaram",
    "Siwan",
  ],
  Chhattisgarh: [
    "Ambikapur",
    "Bhilai",
    "Bilaspur",
    "Dhamtari",
    "Durg",
    "Jagdalpur",
    "Kanker",
    "Kawardha",
    "Korba",
    "Mahasamund",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
  ],
  Goa: ["Curchorem", "Mapusa", "Margao", "Panaji", "Ponda", "Vasco da Gama"],
  Gujarat: [
    "Ahmedabad",
    "Anand",
    "Bharuch",
    "Bhavnagar",
    "Gandhinagar",
    "Godhra",
    "Jamnagar",
    "Junagadh",
    "Mehsana",
    "Morbi",
    "Nadiad",
    "Navsari",
    "Palanpur",
    "Porbandar",
    "Rajkot",
    "Surat",
    "Surendranagar",
    "Vadodara",
    "Valsad",
    "Veraval",
  ],
  Haryana: [
    "Ambala",
    "Bhiwani",
    "Faridabad",
    "Gurugram",
    "Hisar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Chamba",
    "Dharamshala",
    "Hamirpur",
    "Kullu",
    "Mandi",
    "Nahan",
    "Shimla",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Bokaro",
    "Chaibasa",
    "Daltonganj",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "Giridih",
    "Godda",
    "Hazaribagh",
    "Jamshedpur",
    "Ramgarh",
    "Ranchi",
  ],
  Karnataka: [
    "Ballari",
    "Belagavi",
    "Bengaluru",
    "Bidar",
    "Chikkamagaluru",
    "Chitradurga",
    "Davanagere",
    "Hassan",
    "Hospet",
    "Hubballi",
    "Kalaburagi",
    "Kolar",
    "Mandya",
    "Mangaluru",
    "Mysuru",
    "Raichur",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
  ],
  Kerala: [
    "Alappuzha",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kochi",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Burhanpur",
    "Chhindwara",
    "Dewas",
    "Gwalior",
    "Guna",
    "Indore",
    "Jabalpur",
    "Katni",
    "Khandwa",
    "Morena",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Shivpuri",
    "Singrauli",
    "Ujjain",
    "Vidisha",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Chandrapur",
    "Dhule",
    "Ichalkaranji",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Parbhani",
    "Pune",
    "Sangli",
    "Solapur",
    "Thane",
  ],
  Manipur: ["Bishnupur", "Churachandpur", "Imphal", "Senapati", "Thoubal", "Ukhrul"],
  Meghalaya: ["Jowai", "Nongstoin", "Shillong", "Tura", "Williamnagar"],
  Mizoram: ["Aizawl", "Champhai", "Kolasib", "Lunglei", "Serchhip"],
  Nagaland: ["Dimapur", "Kohima", "Mokokchung", "Mon", "Tuensang", "Wokha", "Zunheboto"],
  Odisha: [
    "Angul",
    "Balangir",
    "Balasore",
    "Bargarh",
    "Berhampur",
    "Bhadrak",
    "Bhawanipatna",
    "Bhubaneswar",
    "Boudh",
    "Cuttack",
    "Deogarh",
    "Dhenkanal",
    "Jagatsinghpur",
    "Jajpur",
    "Jeypore",
    "Jharsuguda",
    "Kendrapara",
    "Keonjhar",
    "Koraput",
    "Malkangiri",
    "Baripada",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Paradip",
    "Phulbani",
    "Puri",
    "Rayagada",
    "Rourkela",
    "Sambalpur",
    "Sonepur",
    "Sundargarh",
    "Talcher",
  ],
  Punjab: [
    "Amritsar",
    "Barnala",
    "Bathinda",
    "Faridkot",
    "Firozpur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Moga",
    "Mohali",
    "Patiala",
    "Pathankot",
    "Sangrur",
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Barmer",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Hanumangarh",
    "Jaipur",
    "Jhunjhunu",
    "Jodhpur",
    "Kota",
    "Nagaur",
    "Pali",
    "Sikar",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur",
  ],
  Sikkim: ["Gangtok", "Gyalshing", "Mangan", "Namchi"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dindigul",
    "Erode",
    "Hosur",
    "Kanchipuram",
    "Karur",
    "Kumbakonam",
    "Madurai",
    "Nagercoil",
    "Ooty",
    "Ranipet",
    "Salem",
    "Thanjavur",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
  ],
  Telangana: [
    "Adilabad",
    "Hyderabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Miryalaguda",
    "Nalgonda",
    "Nizamabad",
    "Ramagundam",
    "Siddipet",
    "Suryapet",
    "Warangal",
  ],
  Tripura: ["Agartala", "Ambassa", "Belonia", "Dharmanagar", "Kailashahar"],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Amroha",
    "Ayodhya",
    "Bahraich",
    "Bareilly",
    "Basti",
    "Bulandshahr",
    "Etawah",
    "Farrukhabad",
    "Firozabad",
    "Ghaziabad",
    "Gorakhpur",
    "Hardoi",
    "Jhansi",
    "Kanpur",
    "Lucknow",
    "Mathura",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Noida",
    "Prayagraj",
    "Rae Bareli",
    "Rampur",
    "Saharanpur",
    "Shahjahanpur",
    "Sitapur",
    "Varanasi",
  ],
  Uttarakhand: [
    "Almora",
    "Dehradun",
    "Haldwani",
    "Haridwar",
    "Kashipur",
    "Nainital",
    "Pithoragarh",
    "Rishikesh",
    "Roorkee",
    "Rudrapur",
  ],
  "West Bengal": [
    "Asansol",
    "Baharampur",
    "Bardhaman",
    "Cooch Behar",
    "Darjeeling",
    "Durgapur",
    "Habra",
    "Jalpaiguri",
    "Kharagpur",
    "Kolkata",
    "Krishnanagar",
    "Malda",
    "Medinipur",
    "Raiganj",
    "Siliguri",
    "Howrah",
  ],
  "Andaman and Nicobar Islands": ["Diglipur", "Port Blair"],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Silvassa"],
  Delhi: ["New Delhi", "Delhi"],
  "Jammu and Kashmir": [
    "Anantnag",
    "Baramulla",
    "Jammu",
    "Kathua",
    "Kupwara",
    "Poonch",
    "Rajouri",
    "Sopore",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: ["Leh", "Kargil"],
  Lakshadweep: ["Kavaratti"],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
};

export const INDIA_STATES = Object.keys(INDIA_STATES_CITIES).sort();

export function getCitiesForState(state: string): string[] {
  return INDIA_STATES_CITIES[state] ?? [];
}

export type LocationSuggestion = { state: string; city: string; label: string };

function normalize(value: string): string {
  return value.trim().toLowerCase();
}

// Free-text search over the known state/city list, e.g. typing "jaipur" or
// "odisha" — used for the location search bar's autocomplete.
export function searchLocations(query: string, limit = 6): LocationSuggestion[] {
  const trimmed = normalize(query);
  if (!trimmed) return [];

  const results: LocationSuggestion[] = [];

  for (const state of INDIA_STATES) {
    if (normalize(state).includes(trimmed)) {
      results.push({ state, city: "", label: state });
    }
    for (const city of getCitiesForState(state)) {
      if (normalize(city).includes(trimmed)) {
        results.push({ state, city, label: `${city}, ${state}` });
      }
    }
  }

  results.sort((a, b) => {
    const aStarts = normalize(a.label).startsWith(trimmed) ? 0 : 1;
    const bStarts = normalize(b.label).startsWith(trimmed) ? 0 : 1;
    return aStarts - bStarts;
  });

  return results.slice(0, limit);
}

// Best-effort single match for when the user submits the search bar directly
// instead of picking a suggestion.
export function resolveLocationQuery(query: string): { state: string; city: string } | null {
  const [best] = searchLocations(query, 1);
  return best ? { state: best.state, city: best.city } : null;
}
